# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"create_head": "fastai_custom_head.ipynb",
         "create_cnn_model": "fastai_custom_head.ipynb",
         "cnn_learner": "fastai_custom_head.ipynb",
         "xtra_tfms": "mobilenet_v2_basic.ipynb",
         "get_tfms": "mobilenet_v2_basic.ipynb",
         "to_film_ar": "mobilenet_v2_basic.ipynb",
         "get_data": "mobilenet_v2_basic.ipynb",
         "get_callbacks": "mobilenet_v2_basic.ipynb",
         "cb_estop": "mobilenet_v2_basic.ipynb",
         "metrics": "mobilenet_v2_basic.ipynb",
         "cb_wandb": "mobilenet_v2_basic.ipynb",
         "torch_to_onnx": "pytorch_to_coreml.ipynb",
         "onnx_to_coreml": "pytorch_to_coreml.ipynb",
         "args": "pytorch_to_coreml.ipynb",
         "add_scaler": "pytorch_to_coreml.ipynb",
         "save_coreml_model": "pytorch_to_coreml.ipynb",
         "torch_to_coreml": "pytorch_to_coreml.ipynb",
         "WandbCallback": "wandb_callback.ipynb"}

modules = ["custom_head.py",
           "train_utils.py",
           "convert.py",
           "wandb.py"]

doc_url = "https://Synopsis.github.io/CinemaNet/"

git_url = "https://github.com/Synopsis/CinemaNet/tree/vision_models/"

def custom_doc_links(name): return None
